class AppRoutes {
  AppRoutes._();

  static const String login = '/login';
  static const String register = '/register';
  static const String forgotPassword = '/forgot-password';
  static const String verification = '/verification';
  static const String resetPassword = '/reset-password';
  static const String location = '/location';
  static const String mapPicker = '/map-picker';
  static const String home = '/home';
  static const String foodHome = '/food-home';
  static const String foodSearch = '/food-search';
  static const String foodFavorites = '/food-favorites';
  static const String foodProfile = '/food-profile';
  static const String volunteerHome = '/volunteer-home';
  static const String volunteerMap = '/volunteer/map';
  static const String volunteerSearch = '/volunteer/search';
  static const String volunteerAddAddress = '/volunteer-add-address';
  static const String volunteerProfile = '/volunteer/profile';
  static const String volunteerDetail = '/volunteer/detail';
  static const String volunteerAddListing = '/volunteer/add-listing';
  static const String volunteerListings = '/volunteer/listings';
  static const String businessHome = '/business-home';
  static const String businessProfile = '/business-profile';
  static const String businessApprovals = '/business-approvals';
  static const String businessAddOrder = '/business-add-order';
  static const String foodDetail = '/food-detail';
  static const String foodReserve = '/food-reserve';
  static const String foodProfileEdit = '/food-profile-edit';
  static const String languageSelect = '/language-select';
  static const String foodAllListings = '/food-all-listings';
  static const String volunteerAllListings = '/volunteer-all-listings';
  static const String addresses = '/addresses';
  static const String foodAddAddress = '/food-add-address';
  static const String businessProfileEdit = '/business-profile-edit';
  static const String businessListings = '/business/listings';
  static const String businessEditOrder = '/business/edit-order';
  static const String businessListingDetail = '/business/listing-detail';
  static const String changePassword = '/change-password';
  static const String notification = '/notification';
}
